### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by Xm798** [DizzyTom/GenshinAchievementsExport#1]
感谢提供好用的工具！
有几个小建议：
建议增加 `requirements.txt` 以方便依赖安装，折腾了好久也没装上`paddlepaddle` ……；
建议增加 `.gitignore` 忽略编译器临时目录；
建议修改一下输出结果的`xlsx`表文件名？`test`感觉怪怪的。

**Comment by tendapc** [comment]
paddle怎么装

**Comment by DizzyTom** [comment]
pip install paddlepaddle

**Comment by DizzyTom** [comment]
> paddle怎么装

pip install paddlepaddle

**Comment by tendapc** [comment]
ok

**Comment by tendapc** [comment]
原始超轻量模型ch_PP-OCRv2_det下载不了

**Comment by tendapc** [comment]
![Uploading SWPVI_762%1WQU`TGX)F7P5(1).png…]()

**Comment by tendapc** [comment]
![SWPVI_762%1WQU`TGX)F7P5(1)](https://user-images.githubusercontent.com/69566610/159205170-9538213a-7048-486a-ac1f-ece385dd95e1.png)
