### ISSUE TITLE
分段式成就的比对结果无法识别已完成部分

### ISSUE THREAD

**Issue by Xm798** [DizzyTom/GenshinAchievementsExport#2]
目前三段式成就，不能区分已完成部分和未完成部分

例如：

大地的馈赠 | 获取200次「藏金之花」或「启示之花」的馈藏。 | 大地的馈赠 | 370/400
-- | -- | -- | --
大地的馈赠 | 获取400次「藏金之花」或「启示之花」的馈藏。 | 大地的馈赠 | 370/400
大地的馈赠 | 获取800次「藏金之花」或「启示之花」的馈藏。 | 大地的馈赠 | 370/400

**Comment by DizzyTom** [comment]
同名的系列成就现在应该是可以的，不同名的系列成就自己忽略就行。
