### ISSUE TITLE
成就列表更新

### ISSUE THREAD

**Issue by Wansn-w** [DizzyTom/GenshinAchievementsExport#6]
[2.6全成就列表13国语言]https://files.wansn.top/1/main/achievements/2.6.0)

**Comment by DizzyTom** [comment]
不弄啦，不弄啦。解包都出来了，还要啥文字识别。https://github.com/HolographicHat/genshin-achievement-export ，这个挺不错的。

> [2.6全成就列表13国语言]https://files.wansn.top/1/main/achievements/2.6.0)
